package com.cars.collection.model;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.vaadin.annotations.AutoGenerated;

/*
Model Class Car which is persisted into H2database by Hibernate.
*/
@Entity
@Table
@SuppressWarnings("serial")
public class Car implements Serializable, Cloneable {
	
	
	
	@Id
	@AutoGenerated
	private Long id;

	private String make = "";

	private String model = "";

	private Date checkInDate;
	
    private CarStatus status;
    
   
    

	/*    
Getters and Setters
*/	
    public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public Long getId() {
		return id;
	}

	public Date getCheckInDate() {
		
		return checkInDate;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public CarStatus getStatus() {
		return status;
	}

	public void setStatus(CarStatus status) {
		this.status = status;
	}

	public void setCheckInDate(Date checkInDate){
		this.checkInDate = checkInDate;
	}
	public void setMake(String make) {
		this.make = make;
	}

	public String getMake() {
		return make;
	}


	

	public boolean isPersisted() {
		return id != null;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (this.id == null) {
			return false;
		}

		if (obj instanceof Car && obj.getClass().equals(getClass())) {
			return this.id.equals(((Car) obj).id);
		}

		return false;
	}

	@Override
	public int hashCode() {
		int hash = 5;
		hash = 43 * hash + (id == null ? 0 : id.hashCode());
		return hash;
	}


	@Override
	public Car clone() throws CloneNotSupportedException {
		return (Car) super.clone();
	}

	
}